on: push
name: Deploy website on push
jobs:
web-deploy:
name: Deploy
runs-on: ubuntu-latest
steps:
- name: Get latest code
uses: actions/checkout@v2
- name: Sync files
uses: SamKirkland/FTP-Deploy-Action@4.3.0
with:
server: portfolio-bh-jawad.weebly.com
server-dir: /public_html/
username: u376014963.mediatek-formation-jwd-dev.online
password: ${{ secrets.ftp_password }}
